### ISSUE TITLE
Issue with next/font

### ISSUE THREAD

**Issue by salexpro** [vordgi/next-classnames-minifier#33]
Build is failing when using `next/font`

<img width="700" alt="image" src="https://github.com/vordgi/next-classnames-minifier/assets/4237964/39149cb4-e5b5-49a6-b81c-a87b23f4567d">

`"next-classnames-minifier": "^2.0.0",`

**Comment by vordgi** [comment]
Thanks, Alex. Fixed in version 2.1.0

**Comment by salexpro** [comment]
Somehow it still fails on Vercel even tho it's totally fine with local `npm run build`

<img width="1239" alt="image" src="https://github.com/vordgi/next-classnames-minifier/assets/4237964/a128de8e-39f4-4487-ac7b-63a59bf6fb20">
